config/routes.rb
Rails.application.routes.draw do
  resources :tweets
  root "tweets#index"
  get '/tweeters/search', to: 'tweets#search', as: 'search_tweets'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/tweet.rb
class Tweet < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include Pagy::Backend
end
  

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: %i[ show edit update destroy ]

  # GET /tweets or /tweets.json
  def index
    @tweets = Tweet.order(created_at: :desc)
    @tweets = Tweet.paginate(page: params[:page], per_page: 10)
  end  

  # GET /tweets/1 or /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets or /tweets.json
  def create
    @tweet = Tweet.new(tweet_params)

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to tweet_url(@tweet), notice: "Tweet was successfully created." }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1 or /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to tweet_url(@tweet), notice: "Tweet was successfully updated." }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1 or /tweets/1.json
  def destroy
    @tweet.destroy

    respond_to do |format|
      format.html { redirect_to tweets_url, notice: "Tweet was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def search
    @query = params[:query]
    @tweets = Tweet.where("description LIKE ?", "%#{params[:query]}%")
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tweet_params
      params.require(:tweet).permit(:description, :text, :userName)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    include Pagy::Frontend
  end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TwitterCopia</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
  </head>

  <body>

  <div class='container'>
    <%= yield %>
  </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
  </body>
</html>

app/views/tweets/_form.html.erb
<%= form_with(model: tweet) do |form| %>
  <% if tweet.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
        <% tweet.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :text, style: "display: block" %>
    <%= form.text_field :text %>
  </div>

  <div>
    <%= form.label :userName, style: "display: block" %>
    <%= form.text_field :userName %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/tweets/_tweet.html.erb
<div id="<%= dom_id tweet %>">

  <p>
    <strong>Id:</strong>
    <%= tweet.id %>
  </p>
  <p>
    <strong>Description:</strong>
    <%= tweet.description %>
  </p>

  <p>
    <strong>Text:</strong>
    <%= tweet.text %>
  </p>

  <p>
    <strong>Username:</strong>
    <%= tweet.userName %>
  </p>

</div>

app/views/tweets/edit.html.erb
<h1>Editing tweet</h1>

<%= render "form", tweet: @tweet %>

<br>

<div>
  <%= link_to "Show this tweet", @tweet %> |
  <%= link_to "Back to tweets", tweets_path %>
</div>

app/views/tweets/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Tweets</h1>
  <br>
    <button type="button" class="btn btn-info"><%= link_to "New tweet", new_tweet_path %></button>

  <br>

<%= form_tag(search_tweets_path, method: 'get') do %>
  <%= text_field_tag(:query, params[:query], placeholder: 'Buscar tweets...') %>
  <%= submit_tag('Buscar') %>
<% end %>

<br>

<div id="tweets">
  <% @tweets.reverse_each do |tweet| %>
    <div class="card">
      <div class="card-body">
        <h5 class="card-title"><%= tweet.userName %></h5>
        <h6 class="card-subtitle mb-2 text-muted"><%= tweet.description %></h6>
        <button type="button" class="btn btn-outline-info btn-sm"><%= link_to "Show this tweet", tweet %></button>
      </div>
    </div>
    <br>
  <% end %>

  <%= will_paginate @tweets %>

  <%# <% @tweets.each do |tweet| %>
    <%# <%= render tweet %>
    <%# <p>
      <%= link_to "Show this tweet", tweet %>
    <%# </p>
  <% end %>
<%# </div>

<%= link_to "New tweet", new_tweet_path %> 

app/views/tweets/new.html.erb
<h1>New tweet</h1>

<%= render "form", tweet: @tweet %>

<br>

<div>
  <%= link_to "Back to tweets", tweets_path %>
</div>

app/views/tweets/search.html.erb
<p style="color: green"><%= notice %></p>

<h3>Search Results for "<%= @query %>"</h3>

<% @tweets.each do |tweet| %>
    <div class="card">
      <div class="card-body">
        <h5 class="card-title"><%= tweet.userName %></h5>
        <h6 class="card-subtitle mb-2 text-muted"><%= tweet.description %></h6>
        <button type="button" class="btn btn-info"><%= link_to "Show this tweet", tweet %></button>
      </div>
    </div>
    <br>
     <%= link_to "Back to tweets", tweets_path %>
  <% end %>

app/views/tweets/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @tweet %>

<div>
  <%= link_to "Edit this tweet", edit_tweet_path(@tweet) %> |
  <%= link_to "Back to tweets", tweets_path %>

  <%= button_to "Destroy this tweet", @tweet, method: :delete %>
</div>